### ISSUE TITLE
FR: Support Weekly Notes

### ISSUE THREAD

**Issue by brimwats** [andrewheekin/obsidian-folder-periodic-notes#1]
Pretty straightforward FR--think weekly notes should go in a month folder based on which month the first day of the week is. ISO weeks tend to be the best but it could be up to the user. Here's how I have my vault organized:

![image](https://github.com/andrewheekin/obsidian-folder-periodic-notes/assets/73113656/fd18b5ca-2956-4bb5-82c0-9dc65876142c)

**Comment by andrewheekin** [comment]
@brimwats Added in v1.0.4 ✔️
